apiVersion: v1
kind: Config

current-context: my-kube-playground@my-kube-admin #when we have multiple contexts

clusters:
- name: my-kube-playground
  cluster:
    certificate-authority: ca.crt #alternatively, we can use the data instead of the path in encrypted form:
    certificate-authority-data: sdafsdkjfhjewui5rui32rbsdfbcxnvbnrjklweq23

    server: https://my-kube-playtground:6443

contexts:
- name: my-kube-admin@my-kube-playground
  context:
    cluster: my-kube-playground
    user: my-kube-admin

users:
- name: my-kube-admin
  user:
    client-certificate: admin.crt
    client-key: admin.key
