apiVersion: v1
kind: Config

current-context: my-kube-playground@my-kube-admin #when we have multiple contexts

clusters:
- name: my-kube-playground
  cluster:
    certificate-authority: ca.crt
    server: https://my-kube-playtground:6443

contexts:
- name: my-kube-admin@my-kube-playground
  context:
    cluster: my-kube-playground
    user: my-kube-admin
    namespace: finance #when we switch to this context, we automatically go to this namespace

users:
- name: my-kube-admin
  user:
    client-certificate: admin.crt
    client-key: admin.key

