apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: jane
spec:
  groups:
  - system: authenticated
  signerName: kubernetes.io/kube-apiserver-client
    usages:
  - client auth
  request:
    SADFSDAFW#Q%$WEFSDFXCVDFFGERAFSDZGFDHADFSFSSADGSDAFDSAFERGG #place the encrypted csr code here.