apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce #ReadOnlyMany, ReadWriteOnce, ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # Retain: pv and data retained. Recycle: data deleted, PV retained. Delete: PV and data deleted
  capacity:
    storage: 1Gi
  hostPath: #this can be awsElasticBlockStore for instance in case of cloud storage
    path: /tmp/data